// <auto-generated />
using LexiconMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LexiconMVC.Migrations
{
    [DbContext(typeof(LexiconDbContext))]
    [Migration("20211204140638_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LexiconMVC.Models.PersonModel", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            City = "Hillville",
                            Name = "Anne Green",
                            PhoneNumber = "555-6745-343"
                        },
                        new
                        {
                            PersonId = 2,
                            City = "Metropolis",
                            Name = "Bob Woodyland",
                            PhoneNumber = "555-4342-764"
                        },
                        new
                        {
                            PersonId = 3,
                            City = "Atlantis",
                            Name = "Chris Pillow",
                            PhoneNumber = "555-6433-654"
                        },
                        new
                        {
                            PersonId = 4,
                            City = "Blackforest",
                            Name = "Diana Wald",
                            PhoneNumber = "555-7436-445"
                        },
                        new
                        {
                            PersonId = 5,
                            City = "Woodlands",
                            Name = "Erica Bobcat",
                            PhoneNumber = "555-1272-237"
                        },
                        new
                        {
                            PersonId = 6,
                            City = "Cavetown",
                            Name = "Fred Stone",
                            PhoneNumber = "555-2383-278"
                        },
                        new
                        {
                            PersonId = 7,
                            City = "Castle Island",
                            Name = "Georgina Fiveling",
                            PhoneNumber = "555-1392-865"
                        },
                        new
                        {
                            PersonId = 8,
                            City = "New Ironville",
                            Name = "Hank Red",
                            PhoneNumber = "555-6547-378"
                        },
                        new
                        {
                            PersonId = 9,
                            City = "Leppapolis",
                            Name = "Ivan Bow",
                            PhoneNumber = "555-1010-001"
                        },
                        new
                        {
                            PersonId = 10,
                            City = "Blue Lake",
                            Name = "Joanne Guidebird",
                            PhoneNumber = "555-7256-434"
                        },
                        new
                        {
                            PersonId = 11,
                            City = "Spranley Hill",
                            Name = "Kelly Flood",
                            PhoneNumber = "555-1522-941"
                        },
                        new
                        {
                            PersonId = 12,
                            City = "Silicone Mountain",
                            Name = "Liam Baker",
                            PhoneNumber = "555-4324-555"
                        },
                        new
                        {
                            PersonId = 13,
                            City = "New Nessie City",
                            Name = "Melly Greenfrog",
                            PhoneNumber = "555-3831-197"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
